import type { Metadata } from "next";
import "./globals.css";
import SessionWrapper from "./_components/SessionWrapper";
import Navigation from "./_components/Navigation";
import { Josefin_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RTBooks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body
          className={inter.className}
          style={{ margin: "0", backgroundColor: "black", color: "white" }}
        >
          <Navigation />
          {children}
          <ToastContainer />
        </body>
      </html>
    </SessionWrapper>
  );
}
